variables:
  REPO_NAME: gitlab.com/tellmecomua/dforce.landing

cache:
  paths:
    - image_ref

stages:
  - build_app
  - deploy

build_prod_image:
  stage: build_app
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" -f ci/Dockerfile  .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" > image_ref
  only:
    - master

deploy_prod:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - mkdir -pv ~/.crts
    - cat $PRODUCTION_CA_FILE > ~/.crts/ca.pem
    - cat $PRODUCTION_CERT_FILE > ~/.crts/cert.pem
    - cat $PRODUCTION_KEY_FILE > ~/.crts/key.pem
    - export DOCKER_HOST=$PRODUCTION_MACHINE_ADDR DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=~/.crts/
  script:
    - docker service update --image="$(cat image_ref)" production_dforce_landing
  after_script:
    - rm -rf ~/.crts
    - rm image_ref
  only:
    - master
